# Generated by Django 5.2.6 on 2025-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0005_alter_streak_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
