"""
Django settings for QuickPrep project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from pathlib import Path


import dj_database_url

from dotenv import load_dotenv, find_dotenv


try:
    from . import secrets
    SECRET_KEY = secrets.SECRET_KEY
    EMAIL_HOST_USER = secrets.EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD = secrets.EMAIL_HOST_PASSWORD
except ImportError:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-key-for-testing')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')



# Load .env file - THIS MUST BE FIRST
load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
# This first check for the environment file that what is set on that and if find he set that if not find he set false.
DEBUG = os.getenv("DEBUG", "False").lower() in ("1","true","t")




# settings.py
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", ".onrender.com,localhost,127.0.0.1").split(",")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'streaks.apps.StreaksConfig',
    'accounts.apps.AccountsConfig',
    'home.apps.HomeConfig',
    # 'daily_goals.apps.DailyGoalsConfig',
    'email_service.apps.EmailServiceConfig',
    'Notes.apps.NotesConfig',
    # Cloudinary apps (added these)
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', #Adds the user attribute to every incoming HttpRequest object
    # What is httprequest object is  When a client requests a page or resource from your Django application, Django processes this request and encapsulates all the relevant information into an HttpRequest object.This HttpRequest object is then passed as the first argument to the corresponding view function that handles the request. and it helps to get request like method i.e POST OR GET and sessionid, cookies when the client ask for page.
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware"
]

ROOT_URLCONF = 'QuickPrep.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'QuickPrep.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# The dj_database_url is the python library which take the information from the url we provide for the database and this database contains all the information of the database.
if DEBUG:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600
        )
    }

else:
    # For PythonAnywhere (MySQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'quickprep$default',  # Replace with your actual values
            'USER': 'quickprep',  # Your PythonAnywhere username
            'PASSWORD': secrets.DATABASE_PASSWORD,
            'HOST': 'quickprep.mysql.pythonanywhere-services.com',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # You can customize this
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Project-level static
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT =int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS=True
EMAIL_HOST_USER = 'quickprep001@gmail.com'
DEFAULT_FROM_EMAIL='quickprep001@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # Generate this from Google Account Security settings)
PASSWORD_RESET_TIMEOUT = 3600 



MEDIA_ROOT = BASE_DIR / 'media'


LOGIN_URL = 'login'

# This is cloudaniry setup
import cloudinary
import cloudinary_storage


if secrets:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': secrets.CLOUDINARY_CLOUD_NAME,
        'API_KEY': secrets.CLOUDINARY_API_KEY,
        'API_SECRET': secrets.CLOUDINARY_API_SECRET,
    }
else:
    # Fallback to env vars if secrets.py not found (e.g. some server)
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'

