# Generated by Django 5.2.6 on 2025-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgoals',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersgoals',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
